apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sprintstart

resources:
  - ../../base/sprintstart-ai
  - ../../base/sprintstart-frontend

images:
  - name: ghcr.io/sprintstartproject/sprintstart-ai
    newTag: latest
  - name: ghcr.io/sprintstartproject/sprintstart-frontend
    newTag: latest
