apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sprintstart-dev

resources:
  - ../../../base/sprintstart-keycloak

configMapGenerator:
  - name: sprintstart-keycloak-realm
    files:
      - sprintstart-realm.json
    options:
      disableNameSuffixHash: true

images:
  - name: ghcr.io/sprintstartproject/sprintstart-keycloak
    newTag: dev
