apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sprintstart-keycloak
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - keycloak.sprintstart.local
    secretName: sprintstart-tls
  rules:
  - host: keycloak.sprintstart.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sprintstart-keycloak
            port:
              number: 8080
