apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: sprintstart-backend-dev
  namespace: argocd
spec:
  commonUpdateSettings:
    updateStrategy: digest
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: sprintstart-backend-dev
      images:
        - alias: backend
          imageName: ghcr.io/sprintstartproject/sprintstart-backend:dev
