apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sprintstart-dev

resources:
  - ../../../base/sprintstart-frontend

images:
  - name: ghcr.io/sprintstartproject/sprintstart-frontend
    newTag: dev
