apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sprintstart-dev

resources:
  - ../../../base/sprintstart-frontend

images:
  - name: ghcr.io/sprintstartproject/sprintstart-frontend
    newTag: dev

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.sprintstart.local
    target:
      kind: Ingress
      name: sprintstart-frontend
