apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sprintstart-dev

resources:
  - ../../../base/sprintstart-ai

images:
  - name: ghcr.io/sprintstartproject/sprintstart-ai
    newTag: dev

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      kind: Deployment
      name: sprintstart-ai
